---
- name: Deploy Docker containers to GCP VM
  hosts: all
  gather_facts: false
  vars:
    project_id: parabol-bp-roshan-rathod
    credentials_file: rethinkdb_vm_service_account.json
    user: ansible

  tasks:

    - name: Check if Docker is installed
      command: docker --version
      register: docker_check
      ignore_errors: true
      changed_when: false

    - name: Fail if Docker is not installed
      fail:
        msg: "Docker is not installed on the VM."
      when: docker_check.rc != 0

    - name: Check if Docker Compose is installed
      command: docker-compose --version
      register: docker_compose_check
      ignore_errors: true
      changed_when: false

    - name: Fail if docker-compose is not installed
      fail:
        msg: "docker-compose is not installed on the VM."
      when: docker_compose_check.rc != 0

    - name: Create rethinkdb directory if it doesn't exist
      file:
        path: /home/rethinkdb
        state: directory
        mode: '0755'
        owner: "{{ user }}"
        group: "{{ user }}"
      become: true
      ignore_errors: true

    - name: Copy docker-compose.yaml to VM
      copy:
        src: docker-compose.yaml
        dest: /home/rethinkdb/docker-compose.yaml
        mode: '0644'
      become: true

    - name: Copy service account key to VM
      copy:
        src: "{{credentials_file}}"
        dest: /home/rethinkdb/service_account.json
        mode: '0600'
      become: true

    - name: Stop and remove existing containers
      command: docker-compose -f /home/rethinkdb/docker-compose.yaml down
      become: true
      ignore_errors: true

    - name: Start Docker containers
      command: docker-compose -f /home/rethinkdb/docker-compose.yaml up -d
      become: true